### ISSUE TITLE
sample.py doesn't run

### ISSUE THREAD

**Issue by cmahervir** [evo-design/protein-dpo#2]
There are some stray quotes in there that cause the script to fail. I also added an option to use cpu instead of gpu, and to run from outside the repo. I tried submitting a pull request, but I don't have permissions to create the branch...

**Comment by twidatalla** [comment]
Hi @cmahervir,

Sorry about that. Have you made these changes in your own fork of this repo, but can't make PR from there? I'd rather do that than create another branch just to keep things simple. You can also specify the changes you made in this thread and I can add them in myself.

Best,
Talal

**Comment by TangYiChing** [comment]
Hi,

How can I fix this issue?

```
/protein-dpo/sample.py", line 50, in <module>
    sample_seq_singlechain(model, alphabet, args)
  File "/protein-dpo/sample.py", line 24, in sample_seq_singlechain
    sampled_seq = model.sample(coords, partial_seq=partial_seq, temperature=args.temperature)
  File "/tools/miniconda3/envs/flex/lib/python3.10/site-packages/esm/inverse_folding/gvp_transformer.py", line 104, in sample
    batch_converter([(coords, confidence, None)])
  File "/tools/miniconda3/envs/flex/lib/python3.10/site-packages/esm/inverse_folding/util.py", line 263, in __call__
    confidence = confidence * coord_mask + (-1.) * padding_mask
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

**Comment by twidatalla** [comment]
Hi @TangYiChing,

It looks like what you're showing me are error when you pass or do not pass "device" as an argument to model.sample(). 

I believe the first error is because the model is automatically moved to 'cuda' on line 76 of sample.py, and you did not pass the torch.device('cuda') to be the device argument for  model.sample() so the data is on CPU while the model is on GPU.

The second error is confusing because GVPTransformerModel.sample() is meant to accept 'device' as a keyword argument as you can see [here](https://github.com/facebookresearch/esm/blob/main/esm/inverse_folding/gvp_transformer.py) on line 88. You can also see this argument is passed in their sampling [script](https://github.com/facebookresearch/esm/blob/main/examples/inverse_folding/sample_sequences.py) on line 34. So I wonder if this is because you're not using an up to date version of the esm repo? To see if this is the issue can you try running:

pip install git+https://github.com/facebookresearch/esm.git

This will get you the latest "bleeding-edge" version of the esm repo.

Best,
Talal

**Comment by TangYiChing** [comment]
> Hi @TangYiChing,
> 
> It looks like what you're showing me are error when you pass or do not pass "device" as an argument to model.sample().
> 
> I believe the first error is because the model is automatically moved to 'cuda' on line 76 of sample.py, and you did not pass the torch.device('cuda') to be the device argument for model.sample() so the data is on CPU while the model is on GPU.
> 
> The second error is confusing because GVPTransformerModel.sample() is meant to accept 'device' as a keyword argument as you can see [here](https://github.com/facebookresearch/esm/blob/main/esm/inverse_folding/gvp_transformer.py) on line 88. You can also see this argument is passed in their sampling [script](https://github.com/facebookresearch/esm/blob/main/examples/inverse_folding/sample_sequences.py) on line 34. So I wonder if this is because you're not using an up to date version of the esm repo? To see if this is the issue can you try running:
> 
> pip install git+https://github.com/facebookresearch/esm.git
> 
> This will get you the latest "bleeding-edge" version of the esm repo.
> 
> Best, Talal

Re-installing the esm solves the issue. Thank you, Talal.
